### ISSUE TITLE
Sync database error - ERROR impl.DremioJdbc41Factory :: Failed to create prepared statement: PARSE ERROR: Failure parsing the query

### ISSUE THREAD

**Issue by RonildoSS** [Baoqi/metabase-dremio-driver#11]
[The multimethod metabase.driver/current-user-table-privileges has been added on v0.48.0](https://www.metabase.com/docs/master/developers-guide/driver-changelog#metabase-0480)

![image](https://github.com/Baoqi/metabase-dremio-driver/assets/106629238/eb7ec1d5-b3cd-4c2a-a0ef-2bb5324b7905)

**Comment by Baoqi** [comment]
FYI, just did some small modifications for the fix.

**Comment by RonildoSouza** [comment]
Nice @Baoqi, **feature flag** definitely is great solution, thanks for review 🤩
