### ISSUE TITLE
Subscribe to Metabase Community Driver Authors

### ISSUE THREAD

**Issue by perivamsi** [Baoqi/metabase-dremio-driver#15]
Hi, I am from Metabase. Please subscribe to the [Metabase Community Driver Authors mailing list](https://www.metabase.com/docs/latest/developers-guide/drivers/start#driver-development-announcements). We send information about new Metabase releases and the corresponding changes to the Driver API so you can test new releases before they are out.

**Comment by Baoqi** [comment]
Subscribed. Thanks.
