### ISSUE TITLE
Update the driver to support the changes in Metabase v50

### ISSUE THREAD

**Issue by perivamsi** [Baoqi/metabase-dremio-driver#16]
Please see the [driver API changes](https://www.metabase.com/docs/latest/developers-guide/driver-changelog#metabase-0500) in Metabase v50 and update your driver accordingly.

**Comment by jlcornejo** [comment]
> Consulte los [cambios de la API del controlador](https://www.metabase.com/docs/latest/developers-guide/driver-changelog#metabase-0500) en Metabase v50 y actualice su controlador según corresponda.

Can you help me in more detail to solve this problem please?

**Comment by Baoqi** [comment]
@jlcornejo , I just update the source code to support metabase 0.50.x, please use the latest version/source code to check whether it works fine.

Thanks.
