### ISSUE TITLE
Could not locate metabase/mbql/ files

### ISSUE THREAD

**Issue by cfrancois7** [Baoqi/metabase-dremio-driver#17]
I tried to install the driver but I've got the following error:
```
:cause
 "Could not locate metabase/mbql/util__init.class, metabase/mbql/util.clj or metabase/mbql/util.cljc on classpath.",
 :phase :execution}
    Step "Compile clojure source files" failed with error "Syntax error macroexpanding at (metabase/driver/dremio.clj:1:1)."
```

The metabase/mbql does not exist.
I followed the [install guide](https://www.metabase.com/docs/latest/developers-guide/build.html)

- Install on WSL 2.0
- Metabase v0.50.10

**Comment by Baoqi** [comment]
This is because metabase 0.50.x changed the package name, metabase.mbql.util.

Please update the latest source code of [metabase-dremio-driver](https://github.com/Baoqi/metabase-dremio-driver) and retry. 

Close this issue for now.

Thanks.
