### ISSUE TITLE
Support for Metabase 0.51

### ISSUE THREAD

**Issue by rciszynski** [Baoqi/metabase-dremio-driver#18]
Hi

Dremio driver does not work with Metabase version 0.51.

This is related to the fact that since version 0.51 the methods from metabase.driver.sql.util.unprepare have been removed.

I tried to fix it myself but I do not have enough knowledge. Is there a chance that a new version of the Dremio driver will be available soon?

Best regards

**Comment by Baoqi** [comment]
@rciszynski  just release 1.5.0, which works for metadata 0.51,  but only did some manual test against a local docker dremio instance. You can give it a try. 

Thanks

**Comment by rciszynski** [comment]
It works!
After tests I don't see any errors.

Thanks
