### ISSUE TITLE
no catalog when using a user home schema like "@username"

### ISSUE THREAD

**Issue by fabrice-etanchaud** [Baoqi/metabase-dremio-driver#2]
Hi @Baoqi ,

when configuring a new dremio connection with a user home as schema,
catalog is not retreived.
Maybe an issue with the @ ?

Best regards

**Comment by Baoqi** [comment]
Hi, @fabrice-etanchaud 

Yes, this actually is a bug in dremio side,  I have reported it to dremio:  https://community.dremio.com/t/bug-report-current-schema-returned-extra-double-quote-when-the-current-schema-contains-special-character/7354

and they replied "have opened an internal ticket to address the issue".

But for now, we can work around this by check whether current schema's name matches the regex 

   ^"(@[^"]+)"

and remove the "" if matched. 

Release 1.0.3 has this fix, you can check whether it works if you have time (I did some basic tests)

**Comment by fabrice-etanchaud** [comment]
Thank you @Baoqi ! I will upgrade as soon as possible.

**Comment by fabrice-etanchaud** [comment]
Works like a charm on my side ! Thank you Baoqi.

**Comment by Baoqi** [comment]
Great it works. Let's close this issue for now
