### ISSUE TITLE
metabase how to connect dremio

### ISSUE THREAD

**Issue by Fly0905** [Baoqi/metabase-dremio-driver#4]
Hello, I am using  `docker run -d -p 3000:3000   --mount type=bind,source=/usr/local/jt/deploy-datalake/datalake/metabase/plugins,destination=/plugins   --name metabase metabase/metabase:v0.39.5` 
, but I don't find to how to connect dremio

Trouble refers to teaching,  My Wechat:  wyf19910905

**Comment by Baoqi** [comment]
Please check :

https://github.com/Baoqi/metabase-dremio-driver#how-to-use

on how to put plugin jar into metabase's plugin folder. 


And, after restart metabase, when connect to datasource, it should has "dremio"

**Comment by Fly0905** [comment]
Thanks,  The problem is resolved because I forgot to add executable permissions
