### ISSUE TITLE
Sync Schema Issue

### ISSUE THREAD

**Issue by swakv** [Baoqi/metabase-dremio-driver#8]
After syncing dremio schema to metabase, sync says complete but the schemas page in metabase is empty. Metabase logs dont seem to show anything but dremio logs have the following - 

dremio_1 | 2022-08-12 02:22:24,459 [UserServer-1] WARN c.dremio.sabot.rpc.user.UserSession - Ignoring unknown property: APPLICATIONNAME
dremio_1 | 2022-08-12 02:22:24,460 [UserServer-1] INFO c.d.sabot.rpc.user.UserRPCServer - [USER]: Channel closed /172.21.0.2:31010 <–> /172.21.0.1:65186 (user client)
dremio_1 | 2022-08-12 02:22:24,461 [UserServer-1] INFO com.dremio.ConnectionLog - [121ffbb1-210e-4959-a6f3-293681bedb9f] Connection Closed

Any idea why?

**Comment by MarcoGiorgi** [comment]
Hi @swakv, I'm having the same issue, have you solved it in some way?

**Comment by swakv** [comment]
@MarcoGiorgi I could not solve it unfortunately

**Comment by Baoqi** [comment]
Haven't reproduced yet, close for now.
