### ISSUE TITLE
Issue with filter on date with metabase 0.46

### ISSUE THREAD

**Issue by urba1n** [Baoqi/metabase-dremio-driver#9]
While testing metabase 0.46.0-RC4, a query with a filter (last 12 months) on a timestamp is not working anymore. Here is the error:

`Not supported by Honey SQL 2: ^honeysql.types.SqlCall (honeysql.core/call :timestampadd #sql/raw "month" -12 [:metabase.util.honey-sql-2/typed [:cast [:metabase.util.honey-sql-2/typed :%now {:metabase.util.honeysql-extensions/database-type "timestamptz"}] [:raw "timestamp"]] {:metabase.util.honeysql-extensions/database-type "timestamp"}])
`
Similar filter on mysql databases are fine, so it could be releated to the driver.

Driver interface has changed with 0.46 https://www.metabase.com/docs/master/developers-guide/driver-changelog

**Comment by RonildoSS** [comment]
PR with fix: https://github.com/Baoqi/metabase-dremio-driver/pull/10

**Comment by RonildoSS** [comment]
Link to download pre-release
https://github.com/RonildoSS/metabase-dremio-driver/releases/download/1.1.2-alpha.1/dremio.metabase-driver.jar

**Comment by urba1n** [comment]
@RonildoSS 
Thank you very much, date filtering is working fine now.

I notice the following: my connexion to dremio has 'Use a secure connection (SSL)' on and the host is referenced by an IP address. With the previous version of the dremio driver, this was working. With the new release I get the following error : 'ERROR middleware.catch-exceptions :: Error processing query: Failure in connecting to Dremio: cdjd.com.dremio.exec.rpc.ConnectionFailedException: CONNECTION : SSL negotiation failed'.
Switching 'Use a secure connection (SSL)' off is working fine.

**Comment by rogercezidio** [comment]
Working here too, thanks @RonildoSS

**Comment by Baoqi** [comment]
Fix with new release 1.2.0,  Thanks all.

**Comment by urba1n** [comment]
Thanks @Baoqi
